# Generated by Django 5.2 on 2025-04-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_required', models.IntegerField(default=1)),
                ('is_safe_zone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tiles/')),
            ],
        ),
        migrations.CreateModel(
            name='MapTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='world.map')),
                ('tile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.tiletype')),
            ],
            options={
                'unique_together': {('map', 'x', 'y')},
            },
        ),
    ]
